print('====== DESAFIO 04 ======')
entrada = (input('Digite algo ==> '))
print('Tipo ==> ', type(entrada))
print('Maiúscula ==> ', entrada.isupper())
print('Minúscula ==> ', entrada.islower())
print('Alfanumérico ==> ', entrada.isalnum())
print('Alfabético ==> ', entrada.isalpha())
print('Tabela ASCII ==> ', entrada.isascii())
print('Decimal ==> ', entrada.isdecimal())
print('Dígito ==> ', entrada.isdigit())
print('Identificador ==> ', entrada.isidentifier())
print('Numérico ==> ', entrada.isnumeric())
print('Imprimível ==> ', entrada.isprintable())
print('Espaço ==> ', entrada.isspace())
print('1ª letra maiúscula ==> ', entrada.istitle())
